// Code generated by MockGen. DO NOT EDIT.
// Source: footballsquaregamemicroservices/app (interfaces: FootballSquareGame)

// Package mockfootballsquaregameapp is a generated GoMock package.
package mockfootballsquaregameapp

import (
	app "footballsquaregamemicroservices/app"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	resources "github.com/longvu727/FootballSquaresLibs/util/resources"
)

// MockFootballSquareGame is a mock of FootballSquareGame interface.
type MockFootballSquareGame struct {
	ctrl     *gomock.Controller
	recorder *MockFootballSquareGameMockRecorder
}

// MockFootballSquareGameMockRecorder is the mock recorder for MockFootballSquareGame.
type MockFootballSquareGameMockRecorder struct {
	mock *MockFootballSquareGame
}

// NewMockFootballSquareGame creates a new mock instance.
func NewMockFootballSquareGame(ctrl *gomock.Controller) *MockFootballSquareGame {
	mock := &MockFootballSquareGame{ctrl: ctrl}
	mock.recorder = &MockFootballSquareGameMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFootballSquareGame) EXPECT() *MockFootballSquareGameMockRecorder {
	return m.recorder
}

// CreateDBFootballSquareGame mocks base method.
func (m *MockFootballSquareGame) CreateDBFootballSquareGame(arg0 app.CreateFootballSquareGameParams, arg1 *resources.Resources) (*app.CreateFootballSquareGameResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDBFootballSquareGame", arg0, arg1)
	ret0, _ := ret[0].(*app.CreateFootballSquareGameResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDBFootballSquareGame indicates an expected call of CreateDBFootballSquareGame.
func (mr *MockFootballSquareGameMockRecorder) CreateDBFootballSquareGame(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDBFootballSquareGame", reflect.TypeOf((*MockFootballSquareGame)(nil).CreateDBFootballSquareGame), arg0, arg1)
}

// GetFootballSquareGame mocks base method.
func (m *MockFootballSquareGame) GetFootballSquareGame(arg0 app.GetFootballSquareGameParams, arg1 *resources.Resources) (*app.GetFootballSquareGameResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFootballSquareGame", arg0, arg1)
	ret0, _ := ret[0].(*app.GetFootballSquareGameResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFootballSquareGame indicates an expected call of GetFootballSquareGame.
func (mr *MockFootballSquareGameMockRecorder) GetFootballSquareGame(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFootballSquareGame", reflect.TypeOf((*MockFootballSquareGame)(nil).GetFootballSquareGame), arg0, arg1)
}

// GetFootballSquareGameByGameID mocks base method.
func (m *MockFootballSquareGame) GetFootballSquareGameByGameID(arg0 app.GetFootballSquareGameByGameIDParams, arg1 *resources.Resources) (*app.GetFootballSquareGamesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFootballSquareGameByGameID", arg0, arg1)
	ret0, _ := ret[0].(*app.GetFootballSquareGamesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFootballSquareGameByGameID indicates an expected call of GetFootballSquareGameByGameID.
func (mr *MockFootballSquareGameMockRecorder) GetFootballSquareGameByGameID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFootballSquareGameByGameID", reflect.TypeOf((*MockFootballSquareGame)(nil).GetFootballSquareGameByGameID), arg0, arg1)
}
